services:
  proxy:
    image: nginx:1.26.3-alpine-slim
    hostname: proxy
    ports:
      - "80:80"
    networks:
      - proxy-front
      - proxy-backend
    volumes:
      - type: bind
        read_only: true
        source: ./dev/proxy/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./dev/proxy/logs
        target: /var/log/nginx
    depends_on:
      - front
      - backend
  front:
    build:
      context: ./dev/frontend
      dockerfile: Dockerfile
    hostname: front
    networks:
      - proxy-front
  backend:
    build:
      context: ./dev/backend
      dockerfile: Dockerfile
    hostname: backend
    networks:
      - backend-db
      - backend-firebase
      - proxy-backend
    ports:
      - "8080:80"
    environment:
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
    volumes:
      - type: bind
        read_only: true
        source: ./dev/backend/public
        target: /var/www/html/public
      - type: bind
        read_only: true
        source: ./dev/backend/config
        target: /var/www/html/config
      - type: bind
        read_only: true
        source: ./dev/backend/src
        target: /var/www/html/src
      - type: bind
        source: ./dev/backend/logs
        target: /var/www/html/logs
    depends_on:
      - mysql
  firebase:
    build:
      context: ./dev/firebase
      dockerfile: Dockerfile
    hostname: firebase
    networks:
      - backend-firebase
    ports:
      - "9099:9099"
      - "4000:4000"
    volumes:
      - type: bind
        source: ./dev/firebase/init
        target: /emulator/data
  mysql:
    image: mysql:8.0-oracle
    hostname: mysql
    networks:
      - backend-db
      - phpmyadmin-db
    volumes:
      - type: bind
        read_only: true
        source: ./dev/db/init_sql
        target: /docker-entrypoint-initdb.d
      - type: bind
        read_only: true
        source: ./dev/db/conf.d
        target: /etc/mysql/conf.d
      - type: bind
        source: ./dev/db/logs
        target: /var/log/mysql
      - type: volume
        source: db
        target: /var/lib/mysql
    env_file:
      - dev/db/.env
  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - phpmyadmin-db
    env_file:
      - dev/db/.env
    environment:
      - PMA_HOST=mysql
    ports:
      - "8081:80"
    depends_on:
      - mysql
volumes:
  db:
networks:
  proxy-front:
  proxy-backend:
  backend-db:
  backend-firebase:
  phpmyadmin-db:
