<?php

/**
 * BIDS WebRTC Signaling API
 * PHP version 7.4
 *
 * @package dev_t0r\bids_rtc\signaling
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace dev_t0r\bids_rtc\signaling\model;

use PHPUnit\Framework\TestCase;
use dev_t0r\bids_rtc\signaling\model\SDPOfferInfo;

/**
 * SDPOfferInfoTest Class Doc Comment
 *
 * @package dev_t0r\bids_rtc\signaling\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\bids_rtc\signaling\model\SDPOfferInfo
 */
class SDPOfferInfoTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SDPOfferInfo"
     */
    public function testSDPOfferInfo()
    {
        $testSDPOfferInfo = new SDPOfferInfo();
        $namespacedClassname = SDPOfferInfo::getModelsNamespace() . '\\SDPOfferInfo';
        $this->assertSame('\\' . SDPOfferInfo::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "SDPOfferInfo" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "sdpId"
     */
    public function testPropertySdpId()
    {
        self::markTestIncomplete(
            'Test of "sdpId" property in "SDPOfferInfo" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "offerClientId"
     */
    public function testPropertyOfferClientId()
    {
        self::markTestIncomplete(
            'Test of "offerClientId" property in "SDPOfferInfo" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "offerClientRole"
     */
    public function testPropertyOfferClientRole()
    {
        self::markTestIncomplete(
            'Test of "offerClientRole" property in "SDPOfferInfo" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
        self::markTestIncomplete(
            'Test of "createdAt" property in "SDPOfferInfo" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "offer"
     */
    public function testPropertyOffer()
    {
        self::markTestIncomplete(
            'Test of "offer" property in "SDPOfferInfo" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = SDPOfferInfo::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

