<?php

/**
 * BIDS WebRTC Signaling API
 * PHP version 7.4
 *
 * @package dev_t0r\bids_rtc\signaling
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace dev_t0r\bids_rtc\signaling\api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractSDPExchangeApi Class Doc Comment
 *
 * @package dev_t0r\bids_rtc\signaling\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractSDPExchangeApi
{
    /**
     * DELETE deleteSDPExchange
     * Summary: SDP Exchangeのレコードを削除する
     * Notes: SDP Exchangeレコードを削除する  物理削除のため、復元はできません
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $sdpId SDP ID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteSDPExchange(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $sdpId
    ): ResponseInterface {
        $message = "How about implementing deleteSDPExchange as a DELETE method in dev_t0r\bids_rtc\signaling\api\SDPExchangeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getAnswer
     * Summary: SDP Answer取得
     * Notes: 自身が登録したSDP Offerに対するAnswerを取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getAnswer(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing getAnswer as a GET method in dev_t0r\bids_rtc\signaling\api\SDPExchangeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST registerAnswer
     * Summary: SDP Answer登録
     * Notes: SDP Answerを登録する  ここでAnswerを登録しなかった場合、接続しないものとしてanswer登録待機を解除します。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function registerAnswer(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing registerAnswer as a POST method in dev_t0r\bids_rtc\signaling\api\SDPExchangeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST registerOffer
     * Summary: SDP Offer登録
     * Notes: SDP Offerを登録する  自身がAnswerできるOfferが登録されている場合、同時にそれも取得します。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function registerOffer(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing registerOffer as a POST method in dev_t0r\bids_rtc\signaling\api\SDPExchangeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
