<?php

/**
 * BIDS WebRTC Signaling API
 * PHP version 7.4
 *
 * @package dev_t0r\bids_rtc\signaling
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace dev_t0r\bids_rtc\signaling\api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractApplicationManagementApi Class Doc Comment
 *
 * @package dev_t0r\bids_rtc\signaling\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractApplicationManagementApi
{
    /**
     * GET getApplicationInfo
     * Summary: Applicationの情報を取得する
     * Notes: IDを指定してアプリケーションの情報を取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $appId アプリケーションID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getApplicationInfo(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $appId
    ): ResponseInterface {
        $message = "How about implementing getApplicationInfo as a GET method in dev_t0r\bids_rtc\signaling\api\ApplicationManagementApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
