<?php

/**
 * BIDS WebRTC Signaling API
 * PHP version 7.4
 *
 * @package dev_t0r\bids_rtc\signaling
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace dev_t0r\bids_rtc\signaling\api;

use PHPUnit\Framework\TestCase;
use dev_t0r\bids_rtc\signaling\api\ClientManagementApi;

/**
 * ClientManagementApiTest Class Doc Comment
 *
 * @package dev_t0r\bids_rtc\signaling\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\bids_rtc\signaling\api\ClientManagementApi
 */
class ClientManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteClientInfo
     *
     * Clientの情報を削除する.
     *
     * @covers ::deleteClientInfo
     */
    public function testDeleteClientInfo()
    {
        self::markTestIncomplete(
            'Test of "deleteClientInfo" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getClientInfo
     *
     * Clientの情報を取得する.
     *
     * @covers ::getClientInfo
     */
    public function testGetClientInfo()
    {
        self::markTestIncomplete(
            'Test of "getClientInfo" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getClientInfoList
     *
     * Clientの情報一覧を取得する.
     *
     * @covers ::getClientInfoList
     */
    public function testGetClientInfoList()
    {
        self::markTestIncomplete(
            'Test of "getClientInfoList" method has not been implemented yet.'
        );
    }

    /**
     * Test case for registerClientInfo
     *
     * Clientの情報を登録する.
     *
     * @covers ::registerClientInfo
     */
    public function testRegisterClientInfo()
    {
        self::markTestIncomplete(
            'Test of "registerClientInfo" method has not been implemented yet.'
        );
    }
}
