<?php

/**
 * BIDS WebRTC Signaling API
 * PHP version 7.4
 *
 * @package dev_t0r\bids_rtc\signaling
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace dev_t0r\bids_rtc\signaling\api;

use PHPUnit\Framework\TestCase;
use dev_t0r\bids_rtc\signaling\api\SDPExchangeApi;

/**
 * SDPExchangeApiTest Class Doc Comment
 *
 * @package dev_t0r\bids_rtc\signaling\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\bids_rtc\signaling\api\SDPExchangeApi
 */
class SDPExchangeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteSDPExchange
     *
     * SDP Exchangeのレコードを削除する.
     *
     * @covers ::deleteSDPExchange
     */
    public function testDeleteSDPExchange()
    {
        self::markTestIncomplete(
            'Test of "deleteSDPExchange" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getAnswer
     *
     * SDP Answer取得.
     *
     * @covers ::getAnswer
     */
    public function testGetAnswer()
    {
        self::markTestIncomplete(
            'Test of "getAnswer" method has not been implemented yet.'
        );
    }

    /**
     * Test case for registerAnswer
     *
     * SDP Answer登録.
     *
     * @covers ::registerAnswer
     */
    public function testRegisterAnswer()
    {
        self::markTestIncomplete(
            'Test of "registerAnswer" method has not been implemented yet.'
        );
    }

    /**
     * Test case for registerOffer
     *
     * SDP Offer登録.
     *
     * @covers ::registerOffer
     */
    public function testRegisterOffer()
    {
        self::markTestIncomplete(
            'Test of "registerOffer" method has not been implemented yet.'
        );
    }
}
