<?php

/**
 * BIDS WebRTC Signaling API
 * PHP version 7.4
 *
 * @package dev_t0r\bids_rtc\signaling
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace dev_t0r\bids_rtc\signaling\App;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * RegisterRoutes Class Doc Comment
 *
 * @package dev_t0r\bids_rtc\signaling
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class RegisterRoutes
{
    /** @var array[] list of all api operations */
    private $operations = [
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/signaling',
            'path' => '/',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractAPIInfoApi',
            'userClassname' => 'APIInfoApi',
            'operationId' => 'getApiInfo',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "APIの情報",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ApiInfo"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/signaling',
            'path' => '/apps/{appId}',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractApplicationManagementApi',
            'userClassname' => 'ApplicationManagementApi',
            'operationId' => 'getApplicationInfo',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "そのアプリケーションの情報",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ApplicationInfo"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/signaling',
            'path' => '/clients',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractClientManagementApi',
            'userClassname' => 'ClientManagementApi',
            'operationId' => 'getClientInfoList',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "クライアントの情報一覧",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ClientInfoArray"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // http security schema named 'bearerAuth'
                [
                    'type' => 'http',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT',
                    'isBasic' => false,
                    'isBearer' => true,
                    'isApiKey' => false,
                    'isOAuth' => false,
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '/signaling',
            'path' => '/clients',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractClientManagementApi',
            'userClassname' => 'ClientManagementApi',
            'operationId' => 'registerClientInfo',
            'responses' => [
                '201' => [
                    'jsonSchema' => '{
  "description" : "クライアントの情報",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ClientInfo"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // http security schema named 'bearerAuth'
                [
                    'type' => 'http',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT',
                    'isBasic' => false,
                    'isBearer' => true,
                    'isApiKey' => false,
                    'isOAuth' => false,
                ],
            ],
        ],
        [
            'httpMethod' => 'DELETE',
            'basePathWithoutHost' => '/signaling',
            'path' => '/clients/{clientId}',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractClientManagementApi',
            'userClassname' => 'ClientManagementApi',
            'operationId' => 'deleteClientInfo',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "削除成功"
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
                '404' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // http security schema named 'bearerAuth'
                [
                    'type' => 'http',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT',
                    'isBasic' => false,
                    'isBearer' => true,
                    'isApiKey' => false,
                    'isOAuth' => false,
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/signaling',
            'path' => '/clients/{clientId}',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractClientManagementApi',
            'userClassname' => 'ClientManagementApi',
            'operationId' => 'getClientInfo',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "クライアントの情報",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ClientInfo"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
                '404' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // http security schema named 'bearerAuth'
                [
                    'type' => 'http',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT',
                    'isBasic' => false,
                    'isBearer' => true,
                    'isApiKey' => false,
                    'isOAuth' => false,
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '/signaling',
            'path' => '/answer',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractSDPExchangeApi',
            'userClassname' => 'SDPExchangeApi',
            'operationId' => 'registerAnswer',
            'responses' => [
                '201' => [
                    'jsonSchema' => '{
  "description" : "Answer登録成功"
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // http security schema named 'bearerAuth'
                [
                    'type' => 'http',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT',
                    'isBasic' => false,
                    'isBearer' => true,
                    'isApiKey' => false,
                    'isOAuth' => false,
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '/signaling',
            'path' => '/offer',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractSDPExchangeApi',
            'userClassname' => 'SDPExchangeApi',
            'operationId' => 'registerOffer',
            'responses' => [
                '201' => [
                    'jsonSchema' => '{
  "description" : "Offer登録成功",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/PostSDPOfferInfoResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // http security schema named 'bearerAuth'
                [
                    'type' => 'http',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT',
                    'isBasic' => false,
                    'isBearer' => true,
                    'isApiKey' => false,
                    'isOAuth' => false,
                ],
            ],
        ],
        [
            'httpMethod' => 'DELETE',
            'basePathWithoutHost' => '/signaling',
            'path' => '/exchange/{sdpId}',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractSDPExchangeApi',
            'userClassname' => 'SDPExchangeApi',
            'operationId' => 'deleteSDPExchange',
            'responses' => [
                '204' => [
                    'jsonSchema' => '{
  "description" : "削除成功"
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // http security schema named 'bearerAuth'
                [
                    'type' => 'http',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT',
                    'isBasic' => false,
                    'isBearer' => true,
                    'isApiKey' => false,
                    'isOAuth' => false,
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/signaling',
            'path' => '/answer/{sdpId}',
            'apiPackage' => 'dev_t0r\bids_rtc\signaling\api',
            'classname' => 'AbstractSDPExchangeApi',
            'userClassname' => 'SDPExchangeApi',
            'operationId' => 'getAnswer',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Answer取得成功",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/SDPAnswerInfo"
      }
    }
  }
}',
                ],
                '204' => [
                    'jsonSchema' => '{
  "description" : "Answer未登録"
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
                '404' => [
                    'jsonSchema' => '{
  "description" : "エラー",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/getClientInfoList_401_response"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // http security schema named 'bearerAuth'
                [
                    'type' => 'http',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT',
                    'isBasic' => false,
                    'isBearer' => true,
                    'isApiKey' => false,
                    'isOAuth' => false,
                ],
            ],
        ],
    ];

    /**
     * Add routes to Slim app.
     *
     * @param \Slim\App $app Pre-configured Slim application instance
     *
     * @throws HttpNotImplementedException When implementation class doesn't exists
     */
    public function __invoke(\Slim\App $app): void
    {
        $app->options('/{routes:.*}', function (ServerRequestInterface $request, ResponseInterface $response) {
            // CORS Pre-Flight OPTIONS Request Handler
            return $response;
        });

        // create mock middleware factory
        /** @var \Psr\Container\ContainerInterface */
        $container = $app->getContainer();

        foreach ($this->operations as $operation) {
            $callback = function (ServerRequestInterface $request) use ($operation) {
                $message = "How about extending {$operation['classname']} by {$operation['apiPackage']}\\{$operation['userClassname']} class implementing {$operation['operationId']} as a {$operation['httpMethod']} method?";
                throw new HttpNotImplementedException($request, $message);
            };
            $middlewares = [];

            if (class_exists("\\{$operation['apiPackage']}\\{$operation['userClassname']}")) {
                // Notice how we register the controller using the class name?
                // PHP-DI will instantiate the class for us only when it's actually necessary
                $callback = ["\\{$operation['apiPackage']}\\{$operation['userClassname']}", $operation['operationId']];
            }

            $route = $app->map(
                [$operation['httpMethod']],
                "{$operation['basePathWithoutHost']}{$operation['path']}",
                $callback
            )->setName($operation['operationId']);

            foreach ($middlewares as $middleware) {
                $route->add($middleware);
            }
        }
    }
}
