<?php

/**
 * BIDS WebRTC Signaling API
 * PHP version 7.4
 *
 * @package dev_t0r\bids_rtc\signaling
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\bids_rtc\signaling\model;

use dev_t0r\bids_rtc\signaling\BaseModel;

/**
 * ClientInfoWithToken
 *
 * @package dev_t0r\bids_rtc\signaling\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class ClientInfoWithToken extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\bids_rtc\signaling\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "ClientInfoWithToken",
  "required" : [ "app_id", "client_id", "created_at", "name", "refresh_token" ],
  "type" : "object",
  "properties" : {
    "app_id" : {
      "type" : "string",
      "description" : "アプリID\n",
      "format" : "uuid",
      "readOnly" : true
    },
    "client_id" : {
      "type" : "string",
      "description" : "クライアントID\n",
      "format" : "uuid",
      "readOnly" : true
    },
    "name" : {
      "type" : "string",
      "description" : "名前\n"
    },
    "created_at" : {
      "type" : "string",
      "description" : "作成日時\n",
      "format" : "date-time",
      "readOnly" : true
    },
    "refresh_token" : {
      "type" : "string",
      "description" : "リフレッシュトークン\n",
      "readOnly" : true
    }
  }
}
SCHEMA;
}
