<?php

/**
 * BIDS WebRTC Signaling API
 * PHP version 7.4
 *
 * @package dev_t0r\bids_rtc\signaling
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\bids_rtc\signaling\model;

use dev_t0r\bids_rtc\signaling\BaseModel;

/**
 * SDPOfferInfo
 *
 * @package dev_t0r\bids_rtc\signaling\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class SDPOfferInfo extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\bids_rtc\signaling\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "SDP OfferInfo",
  "required" : [ "created_at", "offer", "offer_client_id", "offer_client_role", "sdp_id" ],
  "type" : "object",
  "properties" : {
    "sdp_id" : {
      "type" : "string",
      "description" : "SDP ID\n",
      "format" : "uuid",
      "readOnly" : true
    },
    "offer_client_id" : {
      "type" : "string",
      "description" : "名前\n",
      "format" : "uuid",
      "readOnly" : true
    },
    "offer_client_role" : {
      "type" : "string",
      "description" : "Offerしたクライアントのロール\n",
      "enum" : [ "provider", "subscriber" ]
    },
    "created_at" : {
      "type" : "string",
      "description" : "作成日時\n",
      "format" : "date-time",
      "readOnly" : true
    },
    "offer" : {
      "type" : "string",
      "description" : "Offer SDP (Base64 encoded)\n",
      "format" : "byte"
    }
  }
}
SCHEMA;
}
